---
title: "Comparison of QUD"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}

library("ggplot2")
library("dplyr")
library(tidyr)
library("data.table")
library(grid)
library(gridExtra)
source("helpers.R")

theme_set(theme_bw())

modals = c("bare", "might",  "could", "think",  "probably",  "looks_like", "bare_not", "other")
modals_labels = c("bare", "might",  "could", "think",  "probably",  "looks like", "bare not", "other")
colscale = scale_color_manual(
  limits = modals_labels,
  values = c(
  "#E6AB02",
  "#7CB637",
  "#4C3B4D",
  "#E7298A",
  "#4381C1",
  "#08415C",
  "#FB3640",
  "#999999"
  )
  )
 # colscale = scale_colour_brewer(limits=modals_labels, drop=F, type="qual", palette="Dark2")
colscale2 = scale_colour_brewer(limits=modals_labels, drop=T, type="qual", palette="Dark2")
colscale_general = scale_color_manual(values=c(
  "#E6AB02",
  "#7CB637",
  "#4C3B4D",
  "#E7298A",
  "#4381C1",
  "#08415C",
  "#FB3640",
  "#999999"
  )
  )


```

```{r data, include=FALSE}

plot_condition = function(fname, qud) {


d = read.csv(fname)

drops <- c("modal1","rating1")
d2 = d[ , !(names(d) %in% drops)]
setnames(d2, old=c("rating2","modal2"), new=c("rating", "modal"))

drops <- c("modal2","rating2")
d3 = d[ , !(names(d) %in% drops)]
setnames(d3, old=c("rating1","modal1"), new=c("rating", "modal"))

drops <- c("modal2", "rating2", "modal1", "rating1")
d4 = d[ , !(names(d) %in% drops)]
d4$rating = d4$rating_other
d4$modal = "other"

d = rbind(d2, d3, d4)

d$modal = factor(d$modal)

d$percentage_blue_f = factor(d$percentage_blue)


d_blue = d %>% filter(., grepl("blue", sentence2))
d_orange = d %>% filter(., grepl("orange", sentence2))

#ggplot(d_orange, aes(x=percentage_blue, y=rating)) + geom_point(aes(col=modal)) +
# geom_smooth(aes(col=modal))

#ggplot(d_blue, aes(x=percentage_blue, y=rating)) + geom_point(aes(col=modal)) +  geom_smooth(aes(col=modal))

d_orange_reverse = d_orange
d_orange_reverse$percentage_blue = 100-d_orange$percentage_blue

d_comparison = rbind(d_blue, d_orange_reverse)
d_comparison$blue= grepl("blue", d_comparison$sentence2)
d_comparison$percentage_blue_f = factor(d_comparison$percentage_blue)

d_comparison$modal = gsub('"', "", d_comparison$modal)
d_comparison$pair = gsub('"', "", d_comparison$pair)


d_comparison$modal = factor(d_comparison$modal, levels=modals, labels = modals_labels, ordered = T)

d_comparison$qud = qud

#p1 = ggplot(d_comparison, aes(x=percentage_blue, y=rating)) + geom_point(aes(col=modal)) +  stat_smooth(aes(col=modal, fill=modal),  method = 'loess', geom="area", alpha=0.5) + ggtitle(d$pair[1]) + xlab("percentage") 

#p1 = ggplot(d_comparison, aes(x=percentage_blue, y=rating)) +  stat_smooth(aes(col=modal, fill=modal),  method = 'loess', geom="area", alpha=0.5) + ggtitle(d$pair[1]) + xlab("percentage") 

d_by_modal_col = d_comparison %>% group_by(modal,percentage_blue, blue, pair) %>% summarise(rating_m = mean(rating), ci_low=ci.low(rating), ci_high=ci.high(rating))

d_by_modal_col$modal = factor(d_by_modal_col$modal, levels=modals, labels = modals_labels, ordered = T)



p1 = ggplot(d_by_modal_col, aes(x=percentage_blue, y=rating_m, group=interaction(modal, blue), col=modal, linetype=blue)) + geom_point(aes(col=modal)) + geom_line() + xlab("percentage") +   geom_errorbar(aes(ymin=rating_m-ci_low, ymax=rating_m+ci_high), width=.1) + facet_wrap(~pair) + colscale

p1a = ggplot(d_comparison %>% group_by(modal,percentage_blue, pair, qud) %>% summarise(rating_m = mean(rating), ci_low=ci.low(rating), ci_high=ci.high(rating)), aes(x=percentage_blue, y=rating_m, group=modal, col=modal)) + geom_point(aes(col=modal), size=1) + geom_line(size=1) + xlab("percentage") +   geom_errorbar(aes(ymin=rating_m-ci_low, ymax=rating_m+ci_high), width=5, size=1) + ylab("mean rating") + facet_wrap(~qud) + colscale   + guides(col=guide_legend(title="Expression", nrow = 4)) + theme(legend.position="bottom", legend.text=element_text(size=9))



p2 = ggplot(d_comparison, aes(x=percentage_blue_f, y=rating, fill=modal)) + 
  geom_boxplot() +
  ggtitle(d$pair[1]) + xlab("percentage") + colscale


d_blue = d_comparison %>% 
  group_by(modal,percentage_blue, blue) %>% 
  summarise(rating_m = mean(rating), ci_low=ci.low(rating), ci_high=ci.high(rating)) %>% 
  filter(blue == T)

d_orange = d_comparison %>% 
  group_by(modal,percentage_blue, blue) %>% 
  summarise(rating_m = mean(rating), ci_low=ci.low(rating), ci_high=ci.high(rating)) %>% 
  filter(blue == F)

d_merged = merge(d_blue, d_orange, by=c("modal", "percentage_blue"))

cat(paste("Correlation between blue and orange mean ratings: ", cor(d_merged$rating_m.x, d_merged$rating_m.y), "\n\n"))

return(list("p1" = p1, "p1a" = p1a, "p2" = p2, d=d_comparison))

}

```


```{r fig.width=3, fig.height=3.5, echo=FALSE}

all_data = data.frame()


plots = plot_condition("../data/8_pre_test_neg-trials.csv",  "don't want")

all_data  = rbind(all_data, plots$d)

plot(plots$p1a)

plots = plot_condition("../../9_pre_test_or//data/9_pre_test_or-trials.csv",  "or")

all_data  = rbind(all_data, plots$d)


plot(plots$p1a)

plots = plot_condition("../../4_comprehension_pre_test/data/4_comprehension_pre_test-prod_trials.csv", "want")

all_data  = rbind(all_data, plots$d)

plot(plots$p1a)

```

```{r fig.width=10, fig.height=3.5, echo=FALSE}


ggplot(all_data %>% group_by(modal,percentage_blue, pair, qud) %>% summarise(rating_m = mean(rating), ci_low=ci.low(rating), ci_high=ci.high(rating)), aes(x=percentage_blue, y=rating_m, group=qud, col=qud)) + geom_point(aes(col=qud), size=1) + geom_line(size=1) + xlab("percentage") +   geom_errorbar(aes(ymin=rating_m-ci_low, ymax=rating_m+ci_high), width=5, size=1) + ylab("mean rating") + facet_wrap(~modal) + guides(col=guide_legend(title="QUD", nrow = 1)) + theme(legend.position="bottom", legend.text=element_text(size=12)) + colscale_general

```

### QUD: or -- individual responses

```{r fig.width=10, fig.height=10.5, echo=FALSE}


all_data %>%
  filter(qud == "or") %>%
  group_by(modal,percentage_blue, pair, workerid) %>% 
  summarise(rating_m = mean(rating), 
            ci_low=ci.low(rating), 
            ci_high=ci.high(rating)) %>%
  ggplot(aes(x=percentage_blue, y=rating_m, group=modal, col=modal)) + 
  geom_point(aes(col=modal), size=1) + 
  geom_line(size=1) +
  xlab("percentage") +
  ylab("mean rating") + 
  facet_wrap(~workerid, ncol=7) + 
  guides(col=guide_legend(title="Expression", nrow = 1)) + 
  theme(legend.position="bottom", legend.text=element_text(size=12)) + colscale



```

```{r }

qud_or_overall_means = all_data %>%
  filter(qud == "or") %>%
  group_by(modal,percentage_blue, pair, workerid) %>% 
  summarise(rating_m = mean(rating)) %>%
  group_by(modal, workerid) %>% 
  summarise(rating_m_overall = mean(rating_m))

qud_or_means =  all_data %>%
  filter(qud == "or") %>%
  group_by(modal,percentage_blue, workerid) %>% 
  summarise(rating_m = mean(rating))


qud_or_merged = merge(qud_or_means, qud_or_overall_means, by=c("workerid", "modal"))

cors = qud_or_merged %>%
  group_by(workerid) %>%
  summarise(corr = cor(rating_m, rating_m_overall))

```
