---
title: "Analysis of speaker-specific adaptation experiment"
author: "Sebastian Schuster"
date: "01/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(data.table)
library(gridExtra)
library(DescTools)
library(splines)
library(stringr)
source("helpers.R")

theme_set(theme_bw())

colscale = scale_color_manual(values=c("#7CB637","#4381C1", "#666666")) 
colscale_fill = scale_fill_manual(values=c("#7CB637","#4381C1", "#666666"))

remove_quotes = function(d) {
  if (!is.null(d$modal)) {
    d$modal = gsub('"', '', d$modal)
  }
  d$color = gsub('"', '', d$color)
  d$speaker_type = gsub('"', '', d$speaker_type)

  return(d)
}


```

```{r data, echo=FALSE}
# Load data

trials = remove_quotes(read.csv("../data/10_talker_specific_adaptation-trials.csv"))
exp_trials = remove_quotes(read.csv("../data/10_talker_specific_adaptation-exp_trials.csv"))

trials[, c("test_order", "first_speaker_type", "confident_speaker")] = str_split(trials$condition, "_", simplify=T)

```

## Catch trial performance

```{r catch_trials, echo=FALSE}

get_correct_catch_trial_counts = function (data) {
  ret = data %>% 
  filter(., catch_trial == 1) %>%
  group_by(workerid) %>%
  summarise(catch_perf = sum(catch_trial_answer_correct))
  
  return(ret)
}

EXCLUDE_BELOW = 11

catch_trial_perf = get_correct_catch_trial_counts(exp_trials)

exclude = catch_trial_perf %>%
  filter(catch_perf < EXCLUDE_BELOW) %>%
  .$workerid


print(paste("Excluded", length(exclude), "participants based on catch-trial performance."))


#final data
d = trials %>% filter(., !(workerid %in% exclude))

```

```{r perf_plot_1, fig.height=2,fig.width=10, echo=FALSE}

cutoff <- data.frame(yintercept=EXCLUDE_BELOW-0.5, cutoff=factor(EXCLUDE_BELOW-0.5))


ggplot(catch_trial_perf, aes(x=factor(workerid), y=catch_perf)) + geom_bar(stat = "identity") + ggtitle("Catch trial performace") + xlab ("participant") + ylab("correct responses") + geom_hline(aes(yintercept=yintercept, linetype=cutoff, color="red"), data=cutoff) + theme(legend.position="none")

```


## Aggregated results


```{r aggregate_plots, echo=FALSE, fig.width=10, fig.height=8}

plot_conditions = function(d, plot_title) {
  drops <- c("modal1","rating1")
  d2 = d[ , !(names(d) %in% drops)]
  setnames(d2, old=c("rating2","modal2"), new=c("rating", "modal"))

  drops <- c("modal2","rating2")
  d3 = d[ , !(names(d) %in% drops)]
  setnames(d3, old=c("rating1","modal1"), new=c("rating", "modal"))

  drops <- c("modal2", "rating2", "modal1", "rating1")
  d4 = d[ , !(names(d) %in% drops)]
  d4$rating = d4$rating_other
  d4$modal = "other"

  d = rbind(d2, d3, d4)

  d$modal = gsub('"', '', d$modal)
  d$modal = factor(d$modal, levels = c("might", "probably", "other"))
  
  d$percentage_blue_f = factor(d$percentage_blue)
  d_blue = d %>% filter(., grepl("blue", sentence2))
  d_orange = d %>% filter(., grepl("orange", sentence2))

  d_orange_reverse = d_orange
  d_orange_reverse$percentage_blue = 100-d_orange$percentage_blue

  d_comparison = rbind(d_blue, d_orange_reverse)
  d_comparison$blue= grepl("blue", d_comparison$sentence2)
  d_comparison$percentage_blue_f = factor(d_comparison$percentage_blue)

  
  
  d_means = d_comparison %>%
  group_by(workerid, percentage_blue, modal, speaker_type) %>% 
  summarise(participant_mean = mean(rating)) %>%
  group_by(percentage_blue, modal, speaker_type) %>%
  summarise(mu = mean(participant_mean),
         ci_high = ci.high(participant_mean), 
         ci_low = ci.low(participant_mean))

  
  p1 = ggplot(d_means, aes(x=percentage_blue, y=mu, col=modal)) + 
  xlab("% blue gumballs") +
  ylab("mean ratings") +
  geom_errorbar(aes(ymin=mu-ci_low, ymax=mu+ci_high), width=.1) +
  geom_line() +
  geom_point(size=1) +
  guides(col=guide_legend(title="Expr.")) +
  colscale +
  theme(legend.position="bottom") + 
  ggtitle(plot_title) +
  facet_wrap(~speaker_type)

  p2 = ggplot(d_comparison, aes(x=percentage_blue_f, y=rating, fill=modal)) + 
  geom_boxplot() +
  ggtitle(plot_title) + xlab("percentage") + colscale_fill +   theme(legend.position="bottom")

  by_participant = ggplot( d_comparison %>%
  group_by(workerid, percentage_blue, modal, speaker_type) %>% 
  summarise(participant_mean = mean(rating)) , 
    aes(x=percentage_blue, y=participant_mean, col=modal, lty=speaker_type)
  ) + 
  xlab("% blue gumballs") +
  ylab("mean ratings") +
  geom_line() +
  geom_point(size=1) +
  guides(col=guide_legend(title="Expr.")) +
  colscale +
  theme(legend.position="bottom") + ggtitle(plot_title) + facet_wrap(~workerid, ncol = 8)
  return(list("p1" = p1, "p2" = p2, "by_participant" = by_participant))

}



  ps1 = plot_conditions(d, "")

  plot(ps1$p1)
  
  plot(ps1$by_participant)


```

## AUC computation

### Method 1

We use the `AUC` function with the `splines` method to directly compute the AUC.

```{r auc_method_1, echo=FALSE}

auc_method2 = function(d) {
  auc = AUC(x=d$percentage_blue, y=d$rating_m, method="spline")
  return(auc)
}


auc_for_participants = function(d, method) {
  
  d[d$color=="orange",]$percentage_blue = 100 - d[d$color=="orange",]$percentage_blue 
  
  aucs = d %>% 
    group_by(workerid) %>% 
    summarize(test_order = first(test_order),
              first_speaker_type = first(first_speaker_type),
              confident_speaker = first(confident_speaker))
    
    
  aucs$auc_might = 0
  aucs$auc_probably = 0

  
  i = 1
  
  for (wid in unique(d$workerid)) {
    d.might_ratings = d %>% 
      filter (., workerid == wid) %>%
      group_by(workerid, percentage_blue) %>%
      summarise(rating_m = mean(rating1))
    
    aucs$auc_might[i] = method(d.might_ratings)

    d.probably_ratings = d %>% 
      filter (., workerid == wid) %>%
      group_by(workerid, percentage_blue) %>%
      summarise(rating_m = mean(rating2))
    
    aucs$auc_probably[i] = method(d.probably_ratings)

    i = i + 1
  }
  
  aucs$auc_diff = aucs$auc_might - aucs$auc_probably
  
  return(aucs)
}

#AUCs for cautious speaker ratings 
aucs.cautious = d %>% filter(speaker_type == "cautious") %>% auc_for_participants(., method=auc_method2)

#AUCs for confident speaker ratings 
aucs.confident = d %>% filter(speaker_type == "confident") %>% auc_for_participants(., method=auc_method2)



```


```{r auc_method1_plots, fig.width=4, fig.height=4, echo=FALSE}

aucs.cautious$cond = "cautious (probably-biased)"

aucs.confident$cond = "confident (might-biased)"


aucs.all = rbind(aucs.cautious, aucs.confident)
aucs.all = aucs.all %>% 
  group_by(., cond) %>% 
  summarise(., auc_diff_m = mean(auc_diff), 
               ci_high = ci.high(auc_diff), 
               ci_low = ci.low(auc_diff))




ggplot(aucs.all, aes(x=0, y=auc_diff_m, color=cond)) +
    geom_errorbar(aes(ymin=auc_diff_m-ci_low, ymax=auc_diff_m+ci_high), width=.1) +
    geom_point() +
    xlab("") +
    ylab("AUC difference (might ratings - probably ratings)") +
    theme(axis.ticks=element_blank(), axis.text.x=element_blank(),
          panel.grid.minor=element_blank(), 
          plot.background=element_blank()) +
    xlim(-.2, .2) 

```

t-test and regression model with control variables:

```{r t_test_method1, echo=FALSE}

print(t.test(aucs.cautious$auc_diff, aucs.confident$auc_diff, var.equal=TRUE))

model = lm(formula= auc_diff ~ cond + test_order + first_speaker_type + confident_speaker, data = rbind(aucs.cautious, aucs.confident))

print(summary(model))

```



