---
title: "Pre Test analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}

library("ggplot2")
library("dplyr")
library(tidyr)
library("data.table")
library(grid)
library(gridExtra)
source("../../0_pre_test/analysis/helpers.R")

theme_set(theme_bw())

modals = c("bare", "might",  "could", "think",  "probably",  "looks_like", "bare_not", "other")
modals_labels = c("bare", "might",  "could", "think",  "probably",  "looks like", "bare not", "other")
colscale = scale_colour_brewer(limits=modals_labels, drop=F, type="qual", palette="Dark2")

remove_quotes = function(d) {
  d$modal = gsub('"', '', d$modal)
  d$color = gsub('"', '', d$color)
  return(d)
}

```

```{r data}

plot_condition = function(fname, comp_trials) {

  fname = 
  
d = read.csv(fname)

drops <- c("modal1","rating1")
d2 = d[ , !(names(d) %in% drops)]
setnames(d2, old=c("rating2","modal2"), new=c("rating", "modal"))

drops <- c("modal2","rating2")
d3 = d[ , !(names(d) %in% drops)]
setnames(d3, old=c("rating1","modal1"), new=c("rating", "modal"))

drops <- c("modal2", "rating2", "modal1", "rating1")
d4 = d[ , !(names(d) %in% drops)]
d4$rating = d4$rating_other
d4$modal = "other"

d = rbind(d2, d3, d4)

d$modal = factor(d$modal)

d$percentage_blue_f = factor(d$percentage_blue)


d_blue = d %>% filter(., grepl("blue", sentence2))
d_orange = d %>% filter(., grepl("orange", sentence2))

#ggplot(d_orange, aes(x=percentage_blue, y=rating)) + geom_point(aes(col=modal)) +
# geom_smooth(aes(col=modal))

#ggplot(d_blue, aes(x=percentage_blue, y=rating)) + geom_point(aes(col=modal)) +  geom_smooth(aes(col=modal))

d_orange_reverse = d_orange
d_orange_reverse$percentage_blue = 100-d_orange$percentage_blue

d_comparison = rbind(d_blue, d_orange_reverse)
d_comparison$blue= grepl("blue", d_comparison$sentence2)
d_comparison$percentage_blue_f = factor(d_comparison$percentage_blue)

d_comparison$modal = gsub('"', "", d_comparison$modal)
d_comparison$pair = gsub('"', "", d_comparison$pair)


d_comparison$modal = factor(d_comparison$modal, levels=modals, labels = modals_labels, ordered = T)

if (!("speaker_cond" %in% colnames(d_comparison))) {
  d_comparison$speaker_cond = "cartoon"
}

#p1 = ggplot(d_comparison, aes(x=percentage_blue, y=rating)) + geom_point(aes(col=modal)) +  stat_smooth(aes(col=modal, fill=modal),  method = 'loess', geom="area", alpha=0.5) + ggtitle(d$pair[1]) + xlab("percentage") 

#p1 = ggplot(d_comparison, aes(x=percentage_blue, y=rating)) +  stat_smooth(aes(col=modal, fill=modal),  method = 'loess', geom="area", alpha=0.5) + ggtitle(d$pair[1]) + xlab("percentage") 

d_by_modal_col = d_comparison %>% group_by(modal,percentage_blue, blue, pair) %>% summarise(rating_m = mean(rating), ci_low=ci.low(rating), ci_high=ci.high(rating))

d_by_modal_col$modal = factor(d_by_modal_col$modal, levels=modals, labels = modals_labels, ordered = T)



p1 = ggplot(d_by_modal_col, aes(x=percentage_blue, y=rating_m, group=interaction(modal, blue), col=modal, linetype=blue)) + geom_point(aes(col=modal)) + geom_line() + xlab("percentage") +   geom_errorbar(aes(ymin=rating_m-ci_low, ymax=rating_m+ci_high), width=.1) + facet_wrap(~pair) + colscale

p1a = ggplot(d_comparison %>% group_by(modal,percentage_blue, pair) %>% summarise(rating_m = mean(rating), ci_low=ci.low(rating), ci_high=ci.high(rating)), aes(x=percentage_blue, y=rating_m, col=modal)) + geom_point(aes(col=modal)) + geom_line() + xlab("percentage") +   geom_errorbar(aes(ymin=rating_m-ci_low, ymax=rating_m+ci_high), width=.1) + ylab("mean rating") + facet_wrap(~pair) + colscale   + guides(col=guide_legend(title="Expression")) #+ theme(legend.position="bottom")

d_comp = d_comparison %>% group_by(modal, color, workerid) %>% mutate(rating_norm = rating**(1/1) * 2 / sum(rating**(1/1))) %>% ungroup()


d_comp$type = "production"
comp_trials$type ="comprehension"

p_comp = ggplot(rbind(d_comp[, colnames(comp_trials)],comp_trials) %>% filter(modal != "other")  %>% filter(modal != "other") %>% group_by(modal,percentage_blue, type) %>% summarise(rating_m = mean((rating_norm)), ci_low=ci.low((rating_norm)), ci_high=ci.high((rating_norm))), aes(x=percentage_blue, linetype=type, y=rating_m, col=modal)) + geom_point(aes(col=modal)) + geom_line() + xlab("percentage") +   geom_errorbar(aes(ymin=rating_m-ci_low, ymax=rating_m+ci_high), width=.1) + ylab("mean rating")  + colscale   + guides(col=guide_legend(title="Expression")) #+ theme(legend.position="bottom")


p1_indiv = ggplot(rbind(d_comp[, colnames(comp_trials)],comp_trials) %>% filter(modal != "other") %>% group_by(modal,percentage_blue, workerid, type) %>% summarise(rating_m = mean(rating_norm), ci_low=ci.low(rating_norm), ci_high=ci.high(rating_norm)), aes(x=percentage_blue, y=rating_m, col=modal, linetype=type)) + geom_point(aes(col=modal)) + geom_line() + xlab("percentage")  + ylab("mean rating") + facet_wrap(~workerid, ncol=4) + colscale   + guides(col=guide_legend(title="Expression")) #+ theme(legend.position="bottom")

p2 = ggplot(d_comparison, aes(x=percentage_blue_f, y=rating, fill=modal)) + 
  geom_boxplot() +
  ggtitle(d$pair[1]) + xlab("percentage") + colscale


d_blue = d_comparison %>% 
  group_by(modal,percentage_blue, blue) %>% 
  summarise(rating_m = mean(rating), ci_low=ci.low(rating), ci_high=ci.high(rating)) %>% 
  filter(blue == T)

d_orange = d_comparison %>% 
  group_by(modal,percentage_blue, blue) %>% 
  summarise(rating_m = mean(rating), ci_low=ci.low(rating), ci_high=ci.high(rating)) %>% 
  filter(blue == F)

d_merged = merge(d_blue, d_orange, by=c("modal", "percentage_blue"))

cat(paste("Correlation between blue and orange mean ratings: ", cor(d_merged$rating_m.x, d_merged$rating_m.y), "\n\n"))

return(list("p1" = p1, "p1a" = p1a, "p2" = p2, "p1_indiv" = p1_indiv, d=d_comparison, "p_comp" = p_comp))

}

```


```{r fig.width=10, fig.height=5, echo=FALSE}

comp_trials = remove_quotes(read.csv("../data/4_comprehension_pre_test-trials.csv"))

comp_trials[comp_trials$color == "orange",]$percentage_blue = 100 - comp_trials[comp_trials$color == "orange",]$percentage_blue

comp_trials = comp_trials %>% group_by(modal, color, workerid) %>% mutate(rating_norm = rating / sum(rating)) %>% ungroup()



ps = plot_condition("../data/4_comprehension_pre_test-prod_trials.csv", comp_trials)

plot(ps$p1a)

plot(ps$p_comp)


ps2 = plot_condition("../../0_pre_test/data/0_pre_test-cond5_2-trials.csv", comp_trials)

plot(ps2$p1a)



```

```{r fig.width=10, fig.height=12, echo=FALSE}

plot(ps$p1_indiv)


```