---
title: "Pre Test analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}

setwd("/Users/sebschu/Dropbox/Uni/RA/adaptation/adaptation/experiments/1_adaptation/analysis/")
library("ggplot2")
library("dplyr")
library(tidyr)
library("data.table")
source("helpers.R")

```

```{r data}

plot_condition = function(condition1, condition2, cond_name) {

  fname1 = paste("../data/1_adaptation-cond", condition1, "-trials.csv", sep="")
  fname2 = paste("../data/1_adaptation-cond", condition2, "-trials.csv", sep="")
print(fname1)
  
d1 = read.csv(fname1)
d2 = read.csv(fname2)

d = rbind(d1,d2)

drops <- c("modal1","rating1")
d2 = d[ , !(names(d) %in% drops)]
setnames(d2, old=c("rating2","modal2"), new=c("rating", "modal"))

drops <- c("modal2","rating2")
d3 = d[ , !(names(d) %in% drops)]
setnames(d3, old=c("rating1","modal1"), new=c("rating", "modal"))

drops <- c("modal2", "rating2", "modal1", "rating1")
d4 = d[ , !(names(d) %in% drops)]
d4$rating = d4$rating_other
d4$modal = "other"

d = rbind(d2, d3, d4)

d$modal = factor(d$modal)

d$percentage_blue_f = factor(d$percentage_blue)


d_blue = d %>% filter(., grepl("blue", sentence2))
d_orange = d %>% filter(., grepl("orange", sentence2))

#ggplot(d_orange, aes(x=percentage_blue, y=rating)) + geom_point(aes(col=modal)) +
# geom_smooth(aes(col=modal))

#ggplot(d_blue, aes(x=percentage_blue, y=rating)) + geom_point(aes(col=modal)) +  geom_smooth(aes(col=modal))

d_orange_reverse = d_orange
d_orange_reverse$percentage_blue = 100-d_orange$percentage_blue

d_comparison = rbind(d_blue, d_orange_reverse)
d_comparison$blue= grepl("blue", d_comparison$sentence2)
d_comparison$percentage_blue_f = factor(d_comparison$percentage_blue)



p1 = ggplot(d_comparison, aes(x=percentage_blue, y=rating)) + geom_point(aes(col=modal)) +  geom_smooth(aes(col=modal,linetype=blue)) + ggtitle(cond_name) + xlab("percentage")

p2 = ggplot(d_comparison, aes(x=percentage_blue_f, y=rating, fill=modal)) + 
  geom_boxplot() +
  ggtitle(cond_name) + xlab("percentage")


return(list("p1" = p1, "p2" = p2))

}

```


```{r}



ps = plot_condition("0", "2", "probably biased")
  plot(ps$p1)
  plot(ps$p2)
  
  ps = plot_condition("1", "3", "might biased")
  plot(ps$p1)
  plot(ps$p2)
  
  ps = plot_condition("0", "0", "probably biased - female")
  plot(ps$p1)
  plot(ps$p2)
  
  ps = plot_condition("2", "2", "probably biased - male")
  plot(ps$p1)
  plot(ps$p2)
  
    ps = plot_condition("1", "1", "might biased - female")
  plot(ps$p1)
  plot(ps$p2)
  
  ps = plot_condition("3", "3", "might biased - male")
  plot(ps$p1)
  plot(ps$p2)
  
  

```